baseURL: "https://statsf18.classes.andrewheiss.com/"
languageCode: en-us
title: Data Science for Public Management
theme: "ath-tufte-hugo_18-19"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.Rhistory$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
  - \.Rproj.user/*
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Reference
      url: /reference/
      weight: 4
    - name: RStudio.cloud
      url: "https://rstudio.cloud"
      weight: 5
    - name: Class chat
      url: "https://gitter.im/byustatsf18/"
      weight: 6
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Ian Adams
  thumbnail: /images/stats_meta.png
  instructor: 
    name: Ian T. Adams
    email: ian.adams@utah.edu
    url: "https://www.ianadamsresearch.com"
    twitter: LiminalMori
    github: ian-adams
    office: Homebase
  course:
    number: PUBPL 6002
    semester: Spring 2021
    days: "Any Day - Asynchronous"
    time: "Any Time - Asynchronous"
    location: "Online"
    twitter: LiminalMori
    dates: "January 19–May 4, 2021"
    github: "ian-adams/MPAstats"
    copyrightYear: "2021"
    contactDetails: >-
      Office hours: [Sign up here.](https://calendly.com/andrewheiss/meeting/)<br><br>E-mail is the best way to get in contact with me—I will respond to all course-related e-mails within 24 hours (*really*).
  university: 
    name: University of Utah
    url: "https://www.utah.edu"
  school:
    name: Department of Political Science
    url: "https://mpp.utah.edu/"
  description: "Use modern statistical and data scientific tools to work with data and improve public management, administration, and policy"
  primaryColor: "#D46600"
  secondaryColor: "#F6E03F"
  credits: >-
    Hex icon by Andrew Heiss. Course materials and design from [Andrew Heiss](https://www.andrewheiss.com/). Color scheme adapted from [October Roads](http://www.colourlovers.com/palette/582235/October_Roads).<br>Course content adapted in part from [MATH 116 (Albert Kim)](https://rudeboybert.github.io/MATH116/), [STA 199 (Mine Çetinkaya-Rundel)](https://www2.stat.duke.edu/courses/Spring18/Sta199/), [SOC 301 (Chester Ismay)](https://ismayc.github.io/soc301_s2017/), and [CONJ 620 (Alison Presmanes Hill)](https://ohsu-conj620.netlify.com/).
  logo:
    url: /images/stats_hires.png
    alt: Data Science for Public Management
  meta:
    twitterSite: "@LiminalMori"
    twitterCreator: "@LiminalMori"
    fbAuthor: ""
