<!DOCTYPE html>
<html lang="en-us"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="https://www.facebook.com/2008/fbml">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Ian Adams">
    <meta name="description" content="Use modern statistical and data scientific tools to work with data and improve public management, administration, and policy">

    <meta name="twitter:card" value="summary_large_image">
    <meta name="twitter:site" content="@LiminalMori">
    <meta name="twitter:title" content="Bootstrapping and confidence intervals | PUBPL 6002: Data Science for Public Management">
    <meta name="twitter:creator" content="@LiminalMori">
    <meta name="twitter:image" content="https://statsf18.classes.andrewheiss.com/images/stats_meta.png">
    <meta name="twitter:description" content="Use modern statistical and data scientific tools to work with data and improve public management, administration, and policy" />

    <meta property="og:site_name" content="PUBPL 6002: Data Science for Public Management"/>
    <meta property="og:title" content="Bootstrapping and confidence intervals | PUBPL 6002: Data Science for Public Management">
    <meta property="og:type" content="article" />
    <meta property="article:author" content="" />
    <meta property="og:url" content="https://statsf18.classes.andrewheiss.com/" />
    <meta property="og:image" content="https://statsf18.classes.andrewheiss.com/images/stats_meta.png">
    <meta property="og:description" content="Use modern statistical and data scientific tools to work with data and improve public management, administration, and policy" />

    <meta name="generator" content="Hugo 0.80.0" />    

    <title>Bootstrapping and confidence intervals | PUBPL 6002: Data Science for Public Management</title>
    <link rel="canonical" href="https://statsf18.classes.andrewheiss.com/class/10-class/">
    <link href="/theme/css/tufte.css" rel="stylesheet">
    <link href="/theme/css/latex.css" rel="stylesheet">
    <link href="/theme/css/custom.css" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style type="text/css">
        .wrap a, .wrap a:visited {
            color: #D46600;
        }

        .wrap a:hover {
            color: #F6E03F;
        }

        .wrap p > a {
            color: #D46600;
        }

        article .sidenote-number:after, article .sidenote:before {
            color: #D46600;
        }

        article .sidenote:before {
            color: #D46600;
        }

        @media (max-width: 760px) {
            label.margin-toggle:not(.sidenote-number) {
                color: #D46600;
            }
        }

        .contrast a, .contrast a:visited {
            color: #D46600; 
        }

        header > nav a {
            color: #D46600;
        }

        .credits a {
            color: #D46600;
        }

        .wrap .tag {
            background: #D46600;
        }
    </style>

    <link rel="shortcut icon" href="https://statsf18.classes.andrewheiss.com/favicon.ico" />
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="https://statsf18.classes.andrewheiss.com/images/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="https://statsf18.classes.andrewheiss.com/images/apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="https://statsf18.classes.andrewheiss.com/images/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="https://statsf18.classes.andrewheiss.com/images/apple-touch-icon-144x144.png" />
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="https://statsf18.classes.andrewheiss.com/images/apple-touch-icon-120x120.png" />
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="https://statsf18.classes.andrewheiss.com/images/apple-touch-icon-152x152.png" />
    <link rel="icon" type="image/png" href="https://statsf18.classes.andrewheiss.com/images/favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="https://statsf18.classes.andrewheiss.com/images/favicon-16x16.png" sizes="16x16" />
    <meta name="application-name" content="PUBPL 6002: Data Science for Public Management"/>
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta name="msapplication-TileImage" content="https://statsf18.classes.andrewheiss.com/images/mstile-144x144.png" />

    
    <link href="https://fonts.googleapis.com/css?family=Oswald:400,600|Roboto:300,400" rel="stylesheet"> 
<link rel="stylesheet" href="//use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">


</head>

<body>
<div class="wrap">
    <header>
        <nav class="group logo-wrap">
            <a href="/" class="logo"><img src="https://statsf18.classes.andrewheiss.com/images/stats_hires.png" alt="Data Science for Public Management"></a>
            <h1 class="websitetitle"><a href="https://statsf18.classes.andrewheiss.com/">PUBPL 6002: Data Science for Public Management</a></h1>
        </nav>
        <nav class="bottom-group">
            
            <a href="/syllabus/">Syllabus</a>
            
            <a href="/schedule/">Schedule</a>
            
            <a href="/assignments/">Assignments</a>
            
            <a href="/reference/">Reference</a>
            
            <a href="https://rstudio.cloud">RStudio.cloud</a>
            
            <a href="https://gitter.im/byustatsf18/">Class chat</a>
            
        </nav>
    </header>


    <article class="group">
    <h1>Bootstrapping and confidence intervals</h1>
    
    <p class="page-date">Materials for class on Thursday, November 8, 2018</p>
    
    
<!-- BLOGDOWN-HEAD -->
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #ffffff;
    color: #a0a0a0;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
div.sourceCode
  { color: #1f1c1b; background-color: #ffffff; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span. { color: #1f1c1b; } /* Normal */
code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
code span.an { color: #ca60ca; } /* Annotation */
code span.at { color: #0057ae; } /* Attribute */
code span.bn { color: #b08000; } /* BaseN */
code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
code span.ch { color: #924c9d; } /* Char */
code span.cn { color: #aa5500; } /* Constant */
code span.co { color: #898887; } /* Comment */
code span.cv { color: #0095ff; } /* CommentVar */
code span.do { color: #607880; } /* Documentation */
code span.dt { color: #0057ae; } /* DataType */
code span.dv { color: #b08000; } /* DecVal */
code span.er { color: #bf0303; text-decoration: underline; } /* Error */
code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
code span.fl { color: #b08000; } /* Float */
code span.fu { color: #644a9b; } /* Function */
code span.im { color: #ff5500; } /* Import */
code span.in { color: #b08000; } /* Information */
code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
code span.op { color: #1f1c1b; } /* Operator */
code span.ot { color: #006e28; } /* Other */
code span.pp { color: #006e28; } /* Preprocessor */
code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
code span.sc { color: #3daee9; } /* SpecialChar */
code span.ss { color: #ff5500; } /* SpecialString */
code span.st { color: #bf0303; } /* String */
code span.va { color: #0057ae; } /* Variable */
code span.vs { color: #bf0303; } /* VerbatimString */
code span.wa { color: #bf0303; } /* Warning */
</style>
<!-- /BLOGDOWN-HEAD -->

<h2>Contents</h2>
<div id="TOC">
<ul>
<li><a href="#slides">Slides</a></li>
<li><a href="#bootstrap-reporting-form">Bootstrap reporting form</a></li>
<li><a href="#live-code">Live code</a></li>
<li><a href="#bootstrapping-with-r">Bootstrapping with R</a><ul>
<li><a href="#in-class-results">In-class results</a></li>
<li><a href="#bootstrapping-with-r-and-infer">Bootstrapping with R and <code>infer</code></a></li>
</ul></li>
<li><a href="#clearest-and-muddiest-things">Clearest and muddiest things</a></li>
</ul>
</div>

<h2 id="slides">Slides</h2>
<p>Download the slides from today’s lecture:</p>
<ul>
<li><a href="/slides/MPA-630_2018-11-08.pdf"><i class="fas fa-file-pdf"></i> PDF (best option)</a></li>
<li><a href="/slides/MPA-630_2018-11-08.pptx"><i class="fas fa-file-powerpoint"></i> PowerPoint</a></li>
</ul>
<figure>
<a href="/slides/MPA-630_2018-11-08.pdf"><img src="/images/slides/slides_2018-11-08.png" alt="First slide" /></a>
</figure>
<h2 id="bootstrap-reporting-form">Bootstrap reporting form</h2>
<p>Go here to report your bootstrap median:</p>
<ul>
<li><i class="fas fa-question-circle"></i> <a href="https://goo.gl/forms/AFQdNb49ffIa4GQ32">Reporting form</a></li>
</ul>
<h2 id="live-code">Live code</h2>
<p>Use this link to see the code that I’m actually typing:</p>
<ul>
<li><i class="fas fa-globe"></i> <a href="https://andhs.co/live-code" class="uri">https://andhs.co/live-code</a></li>
</ul>
<p>I’ve saved the R script to Dropbox, and that link goes to a live version of that file. Refresh or re-open the link as needed to copy/paste code I type up on the screen.</p>
<h2 id="bootstrapping-with-r">Bootstrapping with R</h2>
<p>In class we used the rents of 20 randomly selected apartments in Manhattan to explore how bootstrapping works. Here’s how to do that exploration in R. Load these packages to get started, and download these two datasets (and put them in a folder named “data”):</p>
<ul>
<li><a href="/data/manhattan.csv"><i class="fas fa-table"></i> <code>manhattan.csv</code></a></li>
<li><a href="/data/class_rent_boot.csv"><i class="fas fa-table"></i> <code>class_rent_boot.csv</code></a></li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(moderndive)
<span class="kw">library</span>(infer)
<span class="kw">library</span>(scales)

<span class="co"># Setting a random seed ensures that every random draw will be the same each</span>
<span class="co"># time you run this (and regardless of what computer you run this on)</span>
<span class="kw">set.seed</span>(<span class="dv">1234</span>)</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">manhattan &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/manhattan.csv&quot;</span>)
class_rent_boot &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/class_rent_boot.csv&quot;</span>)</code></pre>
<h3 id="in-class-results">In-class results</h3>
<p>In class, we were interested in the true population-level median 1-bedroom Manhattan apartment rent. This is our unmeasurable population parameter. The only way to get close to it is through sampling and statistics—we can calculate the sample median and calculate a confidence interval for that median to determine how big of a net we have and how confident we are that our confidence interval captured the population parameter.</p>
<p>First, we can look at the sample median. This has nothing to do with bootstrapping yet—this is just the median value of the 20 random apartments.</p>
<pre class="sourceCode r"><code class="sourceCode r">sample_median &lt;-<span class="st"> </span>manhattan <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">stat =</span> <span class="kw">median</span>(rent))
sample_median</code></pre>
<pre><code>## # A tibble: 1 x 1
##    stat
##   &lt;dbl&gt;
## 1  2350</code></pre>
<p>The median rental price is $2,350 a month. Here’s what the distribution of rents from our sample looks like, with the median price overlaid with <code>geom_vline()</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(manhattan, <span class="kw">aes</span>(<span class="dt">x =</span> rent)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">250</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> sample_median<span class="op">$</span>stat, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">labels =</span> dollar) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Rent&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Count&quot;</span>,
       <span class="dt">caption =</span> <span class="st">&quot;Sample median in red&quot;</span>)</code></pre>
<p><img src="/class/10-class_files/figure-html/plot-sample-dist-1.png" width="672" /></p>
<p>How confident are we with this sample median? Is that really representative of the true population parameter? Some of these apartments are under $2,000; some are above $4,000. Is this median really typical?</p>
<p>We can measure our confidence by building a confidence interval for our median, which will allow us to make better inference about the whole population of Manhattan apartments. We can calculate confidence intervals in two ways: math and simulation. We’ll use simulation this week (bootstrapping) and math later on.</p>
<p>In class, you all did a manual bootstrapping process. You took a single sample from our sample of 20 apartments, wrote down the number, replaced the paper, and drew another sample until you had a new bootstrapped sample with 20 observations. Some of these 20 were repeated, which is by design.</p>
<p>You then calculated the median of your bootstrap sample and we made a histogram on the board. Here’s the ggplot version of that histogram, with the sample median marked in red again:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(class_rent_boot, <span class="kw">aes</span>(<span class="dt">x =</span> rent)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">100</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> sample_median<span class="op">$</span>stat, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">labels =</span> dollar) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Rent&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Count&quot;</span>, 
       <span class="dt">caption =</span> <span class="st">&quot;35 bootstrapped medians; sample median in red&quot;</span>)</code></pre>
<p><img src="/class/10-class_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>To find the 95% confidence interval, we need to find the middle 95% of this distribution, or the range from the 2.5% percentile to the 97.5% percentile. We can do this with the <code>quantile()</code> function:</p>
<pre class="sourceCode r"><code class="sourceCode r">class_rent_ci &lt;-<span class="st"> </span>class_rent_boot <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">lower =</span> <span class="kw">quantile</span>(rent, <span class="fl">0.025</span>),
            <span class="dt">upper =</span> <span class="kw">quantile</span>(rent, <span class="fl">0.975</span>))
class_rent_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower upper
##   &lt;dbl&gt; &lt;dbl&gt;
## 1 2171. 3210.</code></pre>
<p>This range means that the 95% confidence interval of rents in Manhattan, based on 35 bootstrapped samples, is ($2,171, $3,210). We are 95% confident that this net captures the true population median.</p>
<h3 id="bootstrapping-with-r-and-infer">Bootstrapping with R and <code>infer</code></h3>
<p>That’s a pretty wide interval though, and we can get a better estimate of the variation in the sample by taking more bootstrapped samples. Instead of 35 manual samples, we can take 1,000 automated samples of the original 20 Manhattan apartments using the <code>infer</code> library.</p>
<p>The standard usage of infer is to <code>specify()</code> the column(s) we’re interested in, <code>generate()</code> a bunch of simulated data based on that column, and then <code>calculate()</code> a sample statistic for the simulated data:</p>
<pre class="sourceCode r"><code class="sourceCode r">boot_rent &lt;-<span class="st"> </span>manhattan <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="co"># Specify the variable of interest</span>
<span class="st">  </span><span class="kw">specify</span>(<span class="dt">response =</span> rent) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="co"># specify(rent ~ NULL)  # This does the same thing</span>
<span class="st">  </span><span class="co"># Generate a bunch of bootstrap samples</span>
<span class="st">  </span><span class="kw">generate</span>(<span class="dt">reps =</span> <span class="dv">1000</span>, <span class="dt">type =</span> <span class="st">&quot;bootstrap&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="co"># Find the median of each sample</span>
<span class="st">  </span><span class="kw">calculate</span>(<span class="dt">stat =</span> <span class="st">&quot;median&quot;</span>)

<span class="co"># See the first few rows</span>
<span class="kw">head</span>(boot_rent)</code></pre>
<pre><code>## # A tibble: 6 x 2
##   replicate  stat
##       &lt;int&gt; &lt;dbl&gt;
## 1         1  2350
## 2         2  2350
## 3         3  2350
## 4         4  2550
## 5         5  2350
## 6         6  2350</code></pre>
<p>We can visualize this with a histogram. This is the same as the in-class histogram above, only now this is based on the medians of 1,000 bootstrapped distributions instead of 35:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(boot_rent, <span class="kw">aes</span>(<span class="dt">x =</span> stat)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">100</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> sample_median<span class="op">$</span>stat, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">labels =</span> dollar) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Rent&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Count&quot;</span>, 
       <span class="dt">caption =</span> <span class="st">&quot;1,000 bootstrapped medians; sample median in red&quot;</span>)</code></pre>
<p><img src="/class/10-class_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Or, instead of using regular ggplot, we can use the <code>visualize()</code> function from <code>infer</code>, which is just a fancy wrapper for ggplot:</p>
<pre class="sourceCode r"><code class="sourceCode r">boot_rent <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">visualize</span>(<span class="dt">obs_stat =</span> sample_median<span class="op">$</span>stat, <span class="dt">obs_stat_color =</span> <span class="st">&quot;red&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">labels =</span> dollar) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Rent&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Count&quot;</span>, 
       <span class="dt">caption =</span> <span class="st">&quot;1,000 bootstrapped medians; sample median in red&quot;</span>)</code></pre>
<pre><code>## Warning: `visualize()` shouldn&#39;t be used to plot p-value. Arguments
## `obs_stat`, `obs_stat_color`, `pvalue_fill`, and `direction` are
## deprecated. Use `shade_p_value()` instead.</code></pre>
<p><img src="/class/10-class_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>We can then find the 95% confidence interval for this distribution with the <code>get_ci()</code> function from <code>infer</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r">boot_rent_ci &lt;-<span class="st"> </span>boot_rent <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">get_ci</span>(<span class="dt">level =</span> <span class="fl">0.95</span>, <span class="dt">type =</span> <span class="st">&quot;percentile&quot;</span>)
boot_rent_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   `2.5%` `97.5%`
##    &lt;dbl&gt;   &lt;dbl&gt;
## 1  2160.    2875</code></pre>
<p>This range means that the 95% confidence interval of rents in Manhattan, based on 1,000 bootstrapped samples from our original 20-apartment sample, is ($2,160, $2,875). We are 95% confident that this net captures the true population median. The lower part of that range is about the same as our by-hand version, but the upper part is considerably smaller.</p>
<p>We can plot this confidence interval in two ways. First, the <code>visualize()</code> way:</p>
<pre class="sourceCode r"><code class="sourceCode r">boot_rent <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">visualize</span>(<span class="dt">endpoints =</span> boot_rent_ci, <span class="dt">direction =</span> <span class="st">&quot;between&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">labels =</span> dollar) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Rent&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Count&quot;</span>, 
       <span class="dt">caption =</span> <span class="st">&quot;1,000 bootstrapped medians; 95% confidence interval in green&quot;</span>)</code></pre>
<pre><code>## Warning: `visualize()` shouldn&#39;t be used to plot confidence interval.
## Arguments `endpoints`, `endpoints_color`, and `ci_fill` are deprecated. Use
## `shade_confidence_interval()` instead.</code></pre>
<p><img src="/class/10-class_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Or the regular ggplot way:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(boot_rent, <span class="kw">aes</span>(<span class="dt">x =</span> stat)) <span class="op">+</span>
<span class="st">  </span><span class="kw">annotate</span>(<span class="dt">geom =</span> <span class="st">&quot;rect&quot;</span>, <span class="dt">xmin =</span> boot_rent_ci<span class="op">$</span><span class="st">`</span><span class="dt">2.5%</span><span class="st">`</span>, <span class="dt">xmax =</span> boot_rent_ci<span class="op">$</span><span class="st">`</span><span class="dt">97.5%</span><span class="st">`</span>,
           <span class="dt">ymin =</span> <span class="op">-</span><span class="ot">Inf</span>, <span class="dt">ymax =</span> <span class="ot">Inf</span>, <span class="dt">alpha =</span> <span class="fl">0.5</span>, <span class="dt">fill =</span> <span class="st">&quot;turquoise&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">100</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> boot_rent_ci<span class="op">$</span><span class="st">`</span><span class="dt">2.5%</span><span class="st">`</span>, <span class="dt">color =</span> <span class="st">&quot;mediumaquamarine&quot;</span>, <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> boot_rent_ci<span class="op">$</span><span class="st">`</span><span class="dt">97.5%</span><span class="st">`</span>, <span class="dt">color =</span> <span class="st">&quot;mediumaquamarine&quot;</span>, <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> sample_median<span class="op">$</span>stat, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">labels =</span> dollar) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Rent&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Count&quot;</span>, 
       <span class="dt">caption =</span> <span class="st">&quot;1,000 bootstrapped medians; sample median in red; 95% confidence interval in green&quot;</span>)</code></pre>
<p><img src="/class/10-class_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<h2 id="clearest-and-muddiest-things">Clearest and muddiest things</h2>
<p>Go to <a href="https://goo.gl/forms/PlPwZGhMOdU9mKfC3">this form</a> and answer these three questions:</p>
<ol style="list-style-type: decimal">
<li>What was the muddiest thing from class today? What are you still wondering about?</li>
<li>What was the clearest thing from class today?</li>
<li>What was the most exciting thing you learned?</li>
</ol>
<p>I’ll compile the questions and send out answers after class.</p>


    </article>

    <footer>
        <hr class="slender">

        <div class="course-info">
        <span class="course-name">
            PUBPL 6002: Data Science for Public Management (Spring 2021)
        </span><br>
        <span>
            <a href="https://www.utah.edu">University of Utah</a> | 
            <a href="https://mpp.utah.edu/">Department of Political Science</a>
        </span>
        </div>

        <ul class="footer-links">
            <li>
            <a href="https://www.ianadamsresearch.com"><i class="fas fa-user"></i> Ian T. Adams</a>
            </li>

            <li>
            <a href="mailto:ian.adams@utah.edu"><i class="fas fa-envelope"></i> ian.adams@utah.edu</a>
            </li>

            <li>
            <i class="far fa-calendar-alt"></i> Any Day - Asynchronous
            </li>

            <li>
            <i class="far fa-clock"></i> Any Time - Asynchronous
            </li>

            <li>
            <i class="fas fa-university"></i> Online
            </li>

            <li>
            <a href="https://twitter.com/LiminalMori"><i class="fab fa-twitter"></i></a>
            </li>

            <li>
            <a href="https://github.com/ian-adams/MPAstats"><i class="fab fa-github"></i></a>
            </li>
        </ul>

        <div class="credits">
        <span class="credit">All content licensed under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.</span><br>

        <span class="credit">Content <i class="fab fa-creative-commons"></i> 2021 <a href="https://www.ianadamsresearch.com">Ian Adams</a></span><br>
        <span class="credit">Hex icon by Andrew Heiss. Course materials and design from <a href="https://www.andrewheiss.com/">Andrew Heiss</a>. Color scheme adapted from <a href="http://www.colourlovers.com/palette/582235/October_Roads">October Roads</a>.<br>Course content adapted in part from <a href="https://rudeboybert.github.io/MATH116/">MATH 116 (Albert Kim)</a>, <a href="https://www2.stat.duke.edu/courses/Spring18/Sta199/">STA 199 (Mine Çetinkaya-Rundel)</a>, <a href="https://ismayc.github.io/soc301_s2017/">SOC 301 (Chester Ismay)</a>, and <a href="https://ohsu-conj620.netlify.com/">CONJ 620 (Alison Presmanes Hill)</a>.</span><br>

        <span class="credit">This site created with the <a href="https://github.com/andrewheiss/ath-tufte-hugo_18-19">ath-tufte-hugo theme</a> in <a href="https://bookdown.org/yihui/blogdown/">blogdown</a> and <a href="https://gohugo.io/">Hugo</a>.</span>
        </div>
    </footer>

    

</div>
</body>
</html>

